# ==========================================
# Google OAuth2 Endpoints (공통 고정값)
# ==========================================
google.token.uri=https://oauth2.googleapis.com/token
google.userinfo.uri=https://www.googleapis.com/oauth2/v3/userinfo


# ==========================================
# [1] Local / Dev 환경 (현재 활성화)
# ==========================================
google.client.id=561584414080-k846ufhfhm2ssumu3sfgna10uk3dsojb.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:8080/login/oauth2/code/google


# ==========================================
# [2] Production (RE-DAY 운영 환경)
# 배포 시 위의 로컬 설정을 주석 처리하고 아래 주석을 해제하여 사용
# ==========================================
# google.client.id=561584414080-dggblrctalh181gksr6u39mkl8hs2ifa.apps.googleusercontent.com
# google.client.secret=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
# google.redirect.uri=https://re-day.com/login/oauth2/code/google